from enum import Enum

class EventType(Enum):
    ADD_JOB = "ADD_JOB"
    STATUS_UPDATE = "STATUS_UPDATE"
    OUTPUT_UPDATE = "OUTPUT_UPDATE"
    HISTORY_APPEND = "HISTORY_APPEND"
    MESSAGE = "MESSAGE"
    FULL_UPDATE = "FULL_UPDATE"
    ON_COMPLETE = "ON_COMPLETE"
    JOB_QUEUED = "JOB_QUEUED"
